### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'port'

### ISSUE THREAD

**Issue by Syed05** [Nomination-NRB/SAM-webui#1]
I am getting this error while running the code.

` File "app.py", line 674, in <module>     app.run(host='0.0.0.0', port=args.port) AttributeError: 'Namespace' object has no attribute 'port'`

**Comment by Nomination-NRB** [comment]
> I am getting this error while running the code.
> 
> ` File "app.py", line 674, in <module> app.run(host='0.0.0.0', port=args.port) AttributeError: 'Namespace' object has no attribute 'port'`

The code is running on linux, you can try replacing args.port with the fixed value 8989
